// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFfpI68Qk9da17rHNlv9-el9V5jWNUkqw',
    appId: '1:894872777462:web:fa2c6047961dcfbb8972d7',
    messagingSenderId: '894872777462',
    projectId: 'kalp-d5813',
    authDomain: 'kalp-d5813.firebaseapp.com',
    storageBucket: 'kalp-d5813.firebasestorage.app',
    measurementId: 'G-4JMLNJNE2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs1W82oHhumGpl_DKQm4fk8BJPq0p3eGo',
    appId: '1:894872777462:android:b327933fbe8c9e928972d7',
    messagingSenderId: '894872777462',
    projectId: 'kalp-d5813',
    storageBucket: 'kalp-d5813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfhth5WWw2rnWKdljZcrJqHZtxc-x-mnE',
    appId: '1:894872777462:ios:8ea251c401b12b558972d7',
    messagingSenderId: '894872777462',
    projectId: 'kalp-d5813',
    storageBucket: 'kalp-d5813.firebasestorage.app',
    iosBundleId: 'com.example.kalpAtisiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFfpI68Qk9da17rHNlv9-el9V5jWNUkqw',
    appId: '1:894872777462:web:3971d1da4e5cd2778972d7',
    messagingSenderId: '894872777462',
    projectId: 'kalp-d5813',
    authDomain: 'kalp-d5813.firebaseapp.com',
    storageBucket: 'kalp-d5813.firebasestorage.app',
    measurementId: 'G-89SDY58REH',
  );

}